#+TITLE: Emacs Configuration File
#+AUTHOR: Manish Koirala
#+DATE: <2026-02-09 Mon>
#+PROPERTY: header-args:elisp :tangle init.el :comments no
#+STARTUP: content


* Essentials
** Melpa
Melpa is the largest online package repository for emacs packages. The code below adds melpa to package archives, a list of remote urls where emacs searches for packages with package.el.
#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  
#+end_src

** Nerd Icons
The nerd-icons package provides the necessary utf-8 icons for dashboard.el, doom-modeline, dired, and treemacs.
#+begin_src elisp
  (use-package nerd-icons ;; Nerd Icons
    :ensure t)
#+end_src

** Mode Line
The default mode line looks boring and old. It has been replaced by a more modern alternative ‘doom-modeline’
#+begin_src elisp
  (use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
#+end_src

** Dashboard
The default tutorial screen looks bland and boring. It has been replaced by a proper dashboard screen.
#+begin_src elisp
  (setq inhibit-startup-message t) 
  (use-package dashboard 
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-startup-banner
  	(cons
  	 (expand-file-name "dashboard/logo.png" user-emacs-directory)
  	 (expand-file-name "dashboard/logo.txt" user-emacs-directory)
  	 ))
    (setq initial-buffer-choice 'dashboard-open)
    (setq dashboard-display-icons-p t)
    (setq dashboard-center-content t)
    (setq dashboard-icon-type 'nerd-icons)
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-heading-shorcut-format " [%s]")
    (setq dashboard-item-shortcuts '((recents   . "r")
  				   (projects  . "p")
  				   (agenda    . "a")))
    (setq dashboard-items '((recents   . 5)
                            (projects  . 6)
                            (agenda    . 3)))
    :after (nerd-icons))

#+end_src


* User Interface (UI)
** Global minor modes
Emacs ships with a default configuration where the menu bar, tool bar and scroll bars are enabled by default. Likewise, a default tutorial screen is displayed when a user starts an emacs session. These settings have been disabled for visual clarity.
#+begin_src elisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

#+end_src

** Font Family
JetBrainsMonoNerdFont is my goto font family for text-editors, terminal-emulators, and IDEs.
#+begin_src elisp
  (add-to-list 'default-frame-alist '(font . "JetBrainsMonoNerdFont-12"))
#+end_src

** Electric Pairs
Electric pairs reduce additional effort to close brackets or quotes while editing text.
#+begin_src elisp
  (electric-pair-mode 1) ; (,{,<,[ are always paired. (brackets - round, curly, angular, big)
  (electric-quote-mode 1) ; ", ’, ‘ are always paired. (quotes - single, double, backticks)
#+end_src

** Org-Mode
*** Auto Indentation
Org-indent provides a visual clarity about which content lies under what heading.
#+begin_src elisp
  (add-hook 'org-mode-hook #'org-indent-mode)
#+end_src
*** UTF-8 Bullets
This package provides a way to set beautiful UTF-8 bullets for nodes within org modes.
#+begin_src elisp
  (use-package org-bullets
    :custom
    (org-bullets-bullet-list '("●" "◉" "○" "◇" "✸" "◦"))
    :ensure t
    :hook
    (org-mode))
#+end_src

** Dired
Dired is the default file browser within emacs. It has been customized to show essential information and hide complex details.
#+begin_src elisp
  (use-package dired ;; Default dired package
    :config
    (setq dired-listing-switches "-l --almost-all --human-readable --group-directories-first --no-group")
    (add-hook 'dired-mode-hook #'dired-hide-details-mode))
#+end_src

** Themes
Activate the default theme if installed. The package ‘doom themes’ is a collection of most popular and beautiful themes in emacs, among which doom-moonlight is my favourite.
#+begin_src elisp
  (unless (package-installed-p 'doom-themes) ;; Install default themes
  (progn
    (package-install 'doom-themes)
    (load-theme 'doom-moonlight t)))

  (if (package-installed-p 'doom-themes)  ;; Activate theme if available.
      (load-theme 'doom-moonlight t))
#+end_src

** Line Numbers
The default line number when enabled through the minor mode ‘(line-numbers-mode)’ displays absolute line numbers. I have changed the configuration to relative which makes it more convinient for navigation.
#+begin_src elisp
  (setq display-line-numbers-type 'relative)
#+end_src

** Visual Line
This minor mode auto-wraps a line into multiple visual lines, enabling the full content of the line to be viewed without overflow.
#+begin_src elisp
  (global-visual-line-mode 1)
#+end_src


* Packages
** Yasnippet
Yasnippet is a powerful snippet plugin for emacs.
#+begin_src elisp
  (use-package yasnippet
    :ensure t)
#+end_src
** Corfu
Corfu is a non-intrusive by default, completions framework for emacs.
#+begin_src elisp
  (use-package corfu
    :ensure t
    :config
    (global-corfu-mode 1))

#+end_src
** Vertico
Vertico provides vertical minibuffer suggestions and completions within emacs.
#+begin_src elisp
  (use-package vertico ;; Vertical minibuffer completions
  :ensure t
  :custom
  (vertico-count 8) ; Show 8 candidates
  (vertico-resize t) ; Grow and resize vertico minibuffer
  (vertico-cycle t) ; Enable cycling for vertico-next/previous
  :config
  (vertico-mode 1))

(use-package savehist ;; Persist history over Emacs restarts. Vertico sorts by history position.
  :init
  (savehist-mode))

#+end_src
** Markdown-mode
Markdown mode is the standard mode for editing markdown files within emacs.
#+begin_src elisp
  (use-package markdown-mode
  :ensure t)
#+end_src
** Which Key
Which key is a useful package that helps a beginner to learn emacs keystrokes by displaying a list of available keys after a given keystroke.
#+begin_src elisp
  (use-package which-key
    :ensure t
    :config
    (which-key-mode 1))

#+end_src
** Mason
Mason handles the local installation and management of language servers, linters, formatters, etc.
#+begin_src elisp
  (use-package mason ;; 
  :ensure t
  :config
  (mason-setup
    (dolist (pkg '("basedpyright" "clangd" "typescript-language-server"))
      (unless (mason-installed-p pkg)
	(ignore-errors (mason-install pkg))))))
#+end_src
** Pyvenv
This package helps in creation, activation and management of python’s virtual environments.
#+begin_src elisp
  (use-package pyvenv
  :ensure t)
#+end_src
